# Generated by Django 4.1.1 on 2022-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0002_pricerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='price',
            field=models.IntegerField(),
        ),
    ]
