# Generated by Django 4.1.1 on 2022-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0004_alter_pricerecord_date_alter_pricerecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
   
    ]
