# Generated by Django 4.1.1 on 2022-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0005_apartment_link_alter_apartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
